### ISSUE TITLE
After 28.02.2019 update of picroft / mycroft cmd_skill stopped to work

### ISSUE THREAD

**Issue by streaktools** [forslund/cmd_skill#1]
Output:

16:24:07.516 - mycroft.skills.core:load_skill:166 - ERROR - Failed to load skill: cmd_skill.forslund
Traceback (most recent call last):
File “/home/pi/mycroft-core/mycroft/skills/core.py”, line 146, in load_skill
raise e
File “/home/pi/mycroft-core/mycroft/skills/core.py”, line 142, in load_skill
skill.initialize()
File “/opt/mycroft/skills/cmd_skill.forslund/init.py”, line 50, in initialize
self.emitter.on(‘CmdSkillRun’, self.run)
AttributeError: ‘CmdSkill’ object has no attribute ‘emitter’

**Comment by forslund** [comment]
I did a simple one line update that should have fixed this now. Let me know how it goes

**Comment by streaktools** [comment]
Yeah, yesterday works, because i checked it. 

But today another some kind of update in mycroft and i have:

11:31:00.057 - mycroft.skills.core:load_skill:148 - INFO - Loaded mycroft-configuration.mycroftai                                                                                                                    
11:31:00.125 - mycroft.skills.core:load_skill:119 - INFO - ATTEMPTING TO LOAD SKILL: cmd_skill with ID cmd_skill                                                                                                     
11:31:00.150 - mycroft.skills.core:config:506 - WARNING - self.config is deprecated.  Switch to using self.setting["whatever"] within your skill.                                                                    
11:31:00.154 - mycroft.skills.core:config:508 - WARNING - Traceback:                                                                                                                                                 
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap                                                                                                                                                    
    self._bootstrap_inner()                                                                                                                                                                                          
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner                                                                                                                                              
    self.run()                                                                                                                                                                                                       
  File "/home/pi/mycroft-core/mycroft/skills/skill_manager.py", line 407, in run                                                                                                                                     
    self._load_or_reload_skill(skill_path) or                                                                                                                                                                        
  File "/home/pi/mycroft-core/mycroft/skills/skill_manager.py", line 344, in _load_or_reload_skill                                                                                                                   
    BLACKLISTED_SKILLS)                                                                                                                                                                                              
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 132, in load_skill                                                                                                                                       
    skill = skill_module.create_skill()                                                                                                                                                                              
  File "/opt/mycroft/skills/cmd_skill/__init__.py", line 67, in create_skill                                                                                                                                         
    return CmdSkill()                                                                                                                                                                                                
  File "/opt/mycroft/skills/cmd_skill/__init__.py", line 34, in __init__                                                                                                                                             
    if self.config:                                                                                                                                                                                                  
                          
but after restarting mycroft seems that cmd_skill work again :)

Thank You 

BTW. 
I wonder who pushing changes to mycroft stable branch , that are not so "stable" :)

**Comment by forslund** [comment]
Nice to hear that it's useful for you :)

I'm one of the maintainers of mycroft so I'm to blame for this. But in our defence it has been deprecated for 6 months and a warning advising to update has been logged...Just me not maintaining my skills properly.

The warning you're seeing now is that the .config is now deprecated and will be removed with the 19.08 release. I'll better get on that :)
